### ISSUE TITLE
No tools generated with 1.0.7

### ISSUE THREAD

**Issue by thegreatersea** [jaredlll08/JSON-Ables#1]
JSON-Ables: 1.0.7
Forge: 1388
Tinkers' Construct: 1.8.5
ExtraTiC: 1.4.4

As the title suggests, when using version 1.0.7 in the above setup and [this json file](http://pastebin.com/xwtq9iRm), JSON-Ables doesn't generate any tool parts. Reverting at least to version 1.0.3 causes them to generate normally, although I haven't tried to test intermediate versions.

**Comment by jaredlll08** [comment]
Please can I have the log file, as I do some error messages.

**Comment by jaredlll08** [comment]
1.8 is no longer supported. 1.8.9 is nearly a year / 3 versions old now, it is time to move on. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
