### ISSUE TITLE
Question regarding this mod

### ISSUE THREAD

**Issue by Sunconure11** [jaredlll08/JSON-ables#10]
So I stumbled upon this mod and wanted to use it in a modpack I am aiding with. The only problem is, we don't have Tinkers Construct, and I just want to use it for Thaumcraft related stuff. Does this mod still require Tinkers Construct as a dependency, or is it possible to make it not require Tinkers Construct? Tinkers Construct is not being added to the pack since we have felt it would stop users from ever playing with the magical tools.

Also, do aspects require an icon, like how most aspects in Thaumcraft have them?

**Comment by jaredlll08** [comment]
IIRC I removed the dependancy :) if not I will do it asap.

**Comment by Sunconure11** [comment]
I was able to run it without Tinkers Construct, therefore, the dependency is gone.
