### ISSUE TITLE
Updating from 0.0.6 to 1.0.3 causes crash

### ISSUE THREAD

**Issue by canilsen** [jaredlll08/JSON-ables#14]
crash-log: http://pastebin.com/JZEnKiWh

This happens even after deleting old jsonables config folder. TTCore is latest version.
Minecraft Forge 10.13.2.1307

Let me know if I can provide more information.

**Comment by jaredlll08** [comment]
http://ci.tterrag.com/
get the latest TTcore form there, because you do not have the latest

**Comment by canilsen** [comment]
Thanks. Did he stop updating via Curse?

**Comment by jaredlll08** [comment]
I am probably using an alpha... however, I have removed the need for ttcore in the latest version

**Comment by canilsen** [comment]
That fixed it. Thanks a lot :)
