### ISSUE TITLE
Is ttCore even needed?

### ISSUE THREAD

**Issue by Claycorp** [jaredlll08/JSON-Ables#9]
On curseforge it says you need ttCore yet it still launches without it. 
A quick search on this repo doesn't make it seem like it's used at all. If that's the case you should update the build.gradle and curseforge.

**Comment by jaredlll08** [comment]
It does not, this mod is kinda dead, I lost motivation for it.

**Comment by Claycorp** [comment]
Alright.

**Comment by jaredlll08** [comment]
Sorry, I will look into reviving it.

**Comment by Claycorp** [comment]
If it works it works. Documenting it would be a bigger help than fixing the command issue.
